#!/usr/bin/env python3
"""
Plot training and validation loss over epochs from LSTM training history.

Reads the loss_history.csv file generated by lstm_exp_window_eval.py and creates
a clean, publication-ready plot showing both training and validation loss curves.
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

def plot_loss_history(history_path="ml_pipeline/results/loss_history.csv", 
                     output_path="ml_plot/training_plots/loss_curves.png"):
    """
    Plot training and validation loss over epochs.
    
    Args:
        history_path: Path to the CSV file containing loss history
        output_path: Path where to save the plot
    """
    
    # Read the training history
    try:
        history_df = pd.read_csv(history_path)
        print(f"✓ Loaded training history from: {history_path}")
        print(f"  → Found {len(history_df)} epochs of training data")
    except FileNotFoundError:
        print(f"❌ Could not find history file: {history_path}")
        print("   Make sure you've run the LSTM training script first!")
        return
    
    # Validate expected columns
    expected_cols = ["epoch", "tr_loss", "va_loss"]
    if not all(col in history_df.columns for col in expected_cols):
        print(f"❌ Expected columns {expected_cols}, but found {list(history_df.columns)}")
        return
    
    # Create the plot
    plt.figure(figsize=(10, 6))
    
    # Plot training and validation loss
    plt.plot(history_df["epoch"], history_df["tr_loss"], 
             label="Training Loss", color="#1f77b4", linewidth=2, marker="o", markersize=4)
    plt.plot(history_df["epoch"], history_df["va_loss"], 
             label="Validation Loss", color="#ff7f0e", linewidth=2, marker="s", markersize=4)
    
    # Customize the plot
    plt.xlabel("Epoch", fontsize=12)
    plt.ylabel("Loss (MSE)", fontsize=12)
    plt.title("LSTM Training Progress: Loss vs Epoch", fontsize=14, fontweight="bold")
    plt.legend(fontsize=11)
    plt.grid(True, alpha=0.3)
    
    # Set reasonable axis limits
    plt.xlim(0.5, len(history_df) + 0.5)
    
    # Add some statistics as text
    final_train_loss = history_df["tr_loss"].iloc[-1]
    final_val_loss = history_df["va_loss"].iloc[-1]
    min_val_loss = history_df["va_loss"].min()
    best_epoch = history_df.loc[history_df["va_loss"].idxmin(), "epoch"]
    
    stats_text = f"Final: Train={final_train_loss:.4f}, Val={final_val_loss:.4f}\n"
    stats_text += f"Best Val: {min_val_loss:.4f} (Epoch {best_epoch})"
    
    plt.text(0.02, 0.98, stats_text, transform=plt.gca().transAxes, 
             fontsize=10, verticalalignment="top", 
             bbox=dict(boxstyle="round,pad=0.3", facecolor="white", alpha=0.8))
    
    # Save the plot
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.show()
    
    print(f"✓ Loss plot saved to: {output_path}")
    print(f"✓ Training summary:")
    print(f"  → Total epochs: {len(history_df)}")
    print(f"  → Final training loss: {final_train_loss:.4f}")
    print(f"  → Final validation loss: {final_val_loss:.4f}")
    print(f"  → Best validation loss: {min_val_loss:.4f} (epoch {best_epoch})")

def main():
    """Main function to create loss plot."""
    print("📊 LSTM Loss Visualization")
    print("=" * 50)
    
    # Default paths relative to project root
    history_path = "ml_pipeline/results/loss_history.csv"
    output_path = "ml_plot/training_plots/loss_curves.png"
    
    # Create the plot
    plot_loss_history(history_path, output_path)

if __name__ == "__main__":
    main()
